baseurl = "/"
languageCode = "en-us"
title = "Alphabet Sigma"
theme = "hyde-hyde"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"

[params]

    authorimage = "/img/foto.jpg"
    description = "Um blog sobre números, letras e suas interseções."

    # options for highlight.js (version, additional languages, and theme)
    highlightjs = true      
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
    [params.social]
	twitter = "kimjoaoun"
	github = "kimjoaoun"
	linkedin = "www.linkedin.com/in/joaoposantos"
	stackoverflow = "https://stackoverflow.com/users/9829398/john-p-s   "
