on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Unit Testing Routine

jobs:
  Testthat-run_tests_r:
    runs-on: ubuntu-latest # <- [1]
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1 # <- [2]

      - name: Install Curl # <- [3]
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev

      - name: Restore R package cache # <- [4-5-7**(?)**]
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Run tests # <- [6]
        run: |
          install.packages("blogdown")
          blogdown::install_hugo()
          blogdown::serve_site()
        shell: Rscript {0}
